// Generated by CoffeeScript 1.3.3
(function() {

  this.Stack = (function() {

    function Stack() {
      this.reset();
    }

    Stack.prototype.push = function(obj) {
      return this.content.push(obj);
    };

    Stack.prototype.pop = function() {
      return this.content.pop();
    };

    Stack.prototype.viewTop = function() {
      return this.content[this.count() - 1];
    };

    Stack.prototype.count = function() {
      return this.content.length;
    };

    Stack.prototype.reset = function() {
      return this.content = [];
    };

    return Stack;

  })();

}).call(this);
