// Generated by CoffeeScript 1.3.3
(function() {

  describe("Parser", function() {
    beforeEach(function() {
      return this.goodHTML = '<!DOCTYPE html><html><head><title>Title</title></head><body><p class="test">A test</p></body></html>';
    });
    return it("breaks up html into an array of tags", function() {
      var parser;
      parser = new Parser(this.goodHTML);
      return expect(parser.stripTags()).toEqual(['<!DOCTYPE html>', '<html>', '<head>', '<title>', '</title>', '</head>', '<body>', '<p class="test">', '</p>', '</body>', '</html>']);
    });
  });

}).call(this);
