// Generated by CoffeeScript 1.3.3
(function() {

  describe("Stack", function() {
    beforeEach(function() {
      this.stack = new Stack;
      this.stack.push(1);
      return this.stack.push(2);
    });
    it("it can push objects onto stack", function() {
      return expect(this.stack.count()).toEqual(2);
    });
    it("removeslast object from stack when popping", function() {
      this.stack.pop();
      return expect(this.stack.count()).toEqual(1);
    });
    it("returns last object in stack when popping", function() {
      return expect(this.stack.pop()).toEqual(2);
    });
    it("resets itself", function() {
      this.stack.reset();
      return expect(this.stack.count()).toEqual(0);
    });
    return it("returns the top item without popping", function() {
      return expect(this.stack.viewTop()).toEqual(2);
    });
  });

}).call(this);
